---
- name: Docker | CE | YUM | Install yum-utils
  yum: name=yum-utils
  become: true

- name: Docker | CE | YUM | Deploy repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  become: true

- name: Docker | CE | YUM | Enable edge repository
  yum_repository:
    name: docker-ce-edge
    description: "Docker CE Edge - x86_64"
    baseurl: "https://download.docker.com/linux/centos/7/x86_64/edge"
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
    file: docker-ce
  become: true

- name: Docker | CE | YUM | Remove older Docker installations
  yum: name={{ item }} state=absent
  with_items:
    - docker
    - docker-common
    - docker-selinux
    - container-selinux
    - docker-engine-selinux
    - docker-engine
    - docker-ce
  become: true

- name: YUM | Install Docker Application
  yum: name=docker-ce-17.03.0.ce-1.el7.centos state=present
  become: true



- name : add user to docker group
  user: name=rts groups=docker append=yes
  become: True

- name : start docker
  service:
    name: docker
    enabled: yes
    state: started
  become: true
