- name: start spark-master
  become: yes
  service: name=spark-master state=started enabled=yes daemon_reload=yes

- name: stop spark-master
  become: yes
  service: name=spark-master state=stopped enabled=no

- name: restart spark-master
  become: yes
  service: name=spark-master state=restarted enabled=yes

- name: start spark-worker
  become: yes
  service: name=spark-worker state=started enabled=yes daemon_reload=yes

- name: stop spark-worker
  become: yes
  service: name=spark-worker state=stopped enabled=no

- name: restart spark-worker
  become: yes
  service: name=spark-worker state=restarted enabled=yes daemon_reload=yes
